### ISSUE TITLE
Can't find dbinfo.php and what is the database name?

### ISSUE THREAD

**Issue by FaridLU** [ngsankha/codejudge#44]

**Comment by ngsankha** [comment]
Look at the page: https://github.com/ngsankha/codejudge/wiki/Installing

Filling in all the details during the installation process creates the `dbinfo.php` file which is used by rest of the system.

**Note:** Codejudge is unmaintained and might not work with the recent PHP versions. Use it on your own risk. I don't have the time to provide support.
